const assert=require('assert/strict'),fs=require('fs'),ts=require('typescript'),Module=require('module');
require.extensions['.ts']=(m,n)=>m._compile(ts.transpileModule(fs.readFileSync(n,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,n);
process.env.BLOB_READ_WRITE_TOKEN='test';process.env.STATE_READ_WRITE_TOKEN='test';process.env.APP_ORIGIN='https://app.test';process.env.PIPELINE_V2='1';
const exportedEditors=[],syncedAds=[];const memory=new Map();let serial=0,submits=0,transcriptions=0,vos=0,exportCount=0,failExport=false,waitTranscribe,waitExport,signalExport;
const real=Module._load;Module._load=function(n,p,i){if(n==='@vercel/blob')return {get:async key=>{const r=memory.get(key);return r?{statusCode:200,stream:new Response(r.body).body,blob:{etag:r.etag}}:null},put:async(key,body,o)=>{const r=memory.get(key);if((o.ifMatch&&r?.etag!==o.ifMatch)||(!o.ifMatch&&r)){const e=Error('conflict');e.name='BlobPreconditionFailedError';throw e;}memory.set(key,{body:Buffer.from(body),etag:String(++serial)});return {etag:String(serial)}}};if(n==='./editor-sync')return {syncAssignedEditor:async id=>{syncedAds.push(id);}};if(n==='./products')return {getProducts:async()=>[]};if(n==='./safe-fetch')return {safeDownload:async url=>({buffer:Buffer.alloc(100),contentType:url.includes('video.mp4')?'video/mp4':'audio/mpeg'})};if(n==='./localize')return {transcribeWithDuration:async()=>{transcriptions++;if(waitTranscribe)await waitTranscribe;return {text:'Source script.',duration:3}},localize:async()=>({uk_script:'UK script.',hooks:['a','b','c'],narration:'UK script.',notes:[],data_gaps:[],funnel:'BOF',ad_desire:'Sleep',ad_angle:'Rest',unique_mechanism:'Magnesium'}),prepareNarration:async t=>t};if(n==='./elevenlabs')return {generateVO:async()=>{vos++;if(signalExport)signalExport();return new ArrayBuffer(100)}};if(n==='./sheets')return {appendToAdminBriefs:async row=>{exportedEditors.push(row.editorId);exportCount++;if(failExport)throw Error('Sheet outage');if(waitExport)await waitExport;return {adId:'MEL-00008'}},updateVoiceover:async()=>{},updateReference:async()=>{}};if(n==='./media')return {mediaBackend:()=> 'blob',existingMedia:async()=>undefined,putMedia:async p=>'https://media.test/'+p};return real.call(this,n,p,i);};
let driveCalls=0;const priorLoad=Module._load;Module._load=function(n,p,i){if(n==='./drive-video')return {driveUploadTarget:async()=>({}),saveOriginalToDrive:async(job,remember)=>{driveCalls++;await remember('drive-file-123');return 'https://drive.google.com/file/d/drive-file-123/view';}};return priorLoad.call(this,n,p,i);};
let calls=[];global.fetch=async (url,init)=>{if(url.endsWith('/api/vmake_submit')){submits++;calls.push(JSON.parse(init.body));return Response.json({task_id:'task-'+submits})}return Response.json({done:true,output_urls:['https://out.test/video.mp4']})};
const jobs=require('../lib/jobs.ts'),pipeline=require('../lib/parallel-pipeline.ts');
const make=async id=>{await jobs.createJob({id,sourceUrl:'https://media.test/source.mp4',audioUrl:'https://media.test/audio.mp3',video:true,videoDestination:'vmake',provider:'openai',generateVo:true,voiceId:'voice'});await require('../lib/store.ts').mutate('job-'+id,null,s=>{s.enhanceVideo=false;});};
(async()=>{
for(const mode of ['enhance','remove','both']){
 const id='vmake-mode-'+mode;await jobs.createJob({id,sourceUrl:'https://media.test/source.mp4',audioUrl:'https://media.test/audio.mp3',video:true,videoDestination:'vmake',vmakeMode:mode,provider:'openai',voiceoverEnabled:false});
 const start=submits;
 for(let n=0;n<10;n++)await pipeline.advanceParallel(id);
 const j=await jobs.getJob(id);assert.equal(j.status,'Complete');assert(j.cleanUrl);assert.equal(submits-start,mode==='both'?2:1);assert.equal(!!j.enhanceTaskId,mode!=='remove');assert.equal(!!j.taskId,mode!=='enhance');
 console.log('PASS '+mode+' completes and submits only selected operations');
}
await assert.rejects(()=>jobs.createJob({id:'invalid-vmake-mode',sourceUrl:'https://media.test/source.mp4',provider:'openai',vmakeMode:'invalid'}),/Invalid VMake mode/);
})().catch(e=>{console.error(e);process.exitCode=1});
