'use client';
import {useState} from 'react';
import FileDrop from '../../szekspir/components/file-drop';
import {extractAudioAsMp3} from '@/lib/audio';
type Result={script:string;checked:number;matches:{id:string;adId:string;name:string;score:number;script:string;comparedWith:string}[]};
export default function CheckScript(){const [file,setFile]=useState<File|null>(null),[script,setScript]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 async function check(){if(busy)return;setBusy(true);setError('');setResult(null);try{const data=new FormData();if(file){setStatus('Preparing audio…');const audio=await extractAudioAsMp3(file);if(audio.size>3800000)throw Error('This recording is too long. Paste its transcript instead.');data.set('audio',audio);}else data.set('script',script);setStatus(file?'Transcribing and searching history…':'Searching history…');const response=await fetch('/api/check-script',{method:'POST',body:data,signal:AbortSignal.timeout(180000)});const answer=await response.json();if(!response.ok)throw Error(answer.error||'Check failed');setResult(answer);setStatus('Check complete.');}catch(e){setError((e as Error).message);setStatus('');}finally{setBusy(false);}}
 return <main className="wrap"><a href="/">← Admin / Home</a><h1>Was this ad already ripped?</h1><p>Upload a video or audio file, or paste its script to compare it with SZEKSPIR history.</p><section className="panel"><FileDrop purpose="check" files={file?[file]:[]} disabled={busy} onChange={files=>{setFile(files[0]||null);setResult(null);}}/><label>Or paste a script<textarea disabled={busy||!!file} rows={8} value={script} onChange={e=>setScript(e.target.value)} placeholder="Original or localised script…"/></label><button className="check" disabled={busy||(!file&&!script.trim())} onClick={check}>{busy?'Checking…':'Check history'}</button><p role="status">{status}</p>{error&&<p role="alert">{error}</p>}</section>{result&&<section><h2>{(result.matches[0]?.score||0)>=85?'A very similar script is already in history':(result.matches[0]?.score||0)>=50?'Possible match — compare the scripts':'No close match found'}</h2><p>Compared with {result.checked} saved ads. Similarity is based on wording, not the video’s visuals. A different script may go undetected.</p><details><summary>Uploaded / pasted transcript</summary><p className="text">{result.script}</p></details>{result.matches.map(m=><article className="panel" key={m.id}><h3>{m.adId||m.name} · {m.score}% text similarity</h3><p>{m.name} · {m.comparedWith}</p><a href={`/szekspir?job=${m.id}`} target="_blank" rel="noopener noreferrer">Open saved ad ↗</a><details><summary>Compare saved script</summary><p className="text">{m.script}</p></details></article>)}</section>}<style jsx>{`.panel{background:var(--card);padding:24px;border:1px solid var(--border);border-radius:16px;margin:24px 0}label{display:block;font-weight:600;margin:16px 0}input,textarea{display:block;margin-top:10px;max-width:100%;width:100%;font:inherit}textarea{border:1px solid var(--border);border-radius:10px;padding:12px;background:var(--bg);color:var(--text)}button{padding:10px 16px;border-radius:9px;border:1px solid var(--border);cursor:pointer}.check{background:#16834c;color:white}button:disabled{opacity:.5;cursor:default}.text{white-space:pre-wrap;line-height:1.65}summary{cursor:pointer;margin-top:18px}[role=alert]{color:#b42318}h1{letter-spacing:0}`}</style></main>;
}
